"""empty message

Revision ID: 01f0ff13936f
Revises: 8a3e78465dbf
Create Date: 2024-07-02 19:28:46.163815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f0ff13936f'
down_revision = '8a3e78465dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('czds_login', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('czds_password', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.drop_column('czds_password')
        batch_op.drop_column('czds_login')

    # ### end Alembic commands ###
