"""empty message

Revision ID: 6cf7818349c2
Revises: d38a799f88ec
Create Date: 2024-07-03 23:57:53.597944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf7818349c2'
down_revision = 'd38a799f88ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.drop_constraint('available_domains_domain_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'domains', ['domain_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('unavailable_domains', schema=None) as batch_op:
        batch_op.drop_constraint('unavailable_domains_domain_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'domains', ['domain_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_domains', schema=None) as batch_op:
        batch_op.drop_constraint('user_domains_domain_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'domains', ['domain_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_domains_domain_id_fkey', 'domains', ['domain_id'], ['id'])

    with op.batch_alter_table('unavailable_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('unavailable_domains_domain_id_fkey', 'domains', ['domain_id'], ['id'])

    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('available_domains_domain_id_fkey', 'domains', ['domain_id'], ['id'])

    # ### end Alembic commands ###
