"""empty message

Revision ID: 6f63996c9609
Revises: 6cf7818349c2
Create Date: 2024-07-04 00:03:05.417980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f63996c9609'
down_revision = '6cf7818349c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_stats', schema=None) as batch_op:
        batch_op.drop_constraint('keyword_stats_keyword_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'keywords', ['keyword_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint('token_blacklist_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_domains', schema=None) as batch_op:
        batch_op.drop_constraint('user_domains_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.drop_constraint('user_envs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_envs_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_domains_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('token_blacklist_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('keyword_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('keyword_stats_keyword_id_fkey', 'keywords', ['keyword_id'], ['id'])

    # ### end Alembic commands ###
