"""empty message

Revision ID: 7f282bddb6ac
Revises: 
Create Date: 2024-07-19 17:06:27.775303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f282bddb6ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('available_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('moz_da', sa.Integer(), nullable=True),
    sa.Column('moz_pa', sa.Integer(), nullable=True),
    sa.Column('ahrefs_dr', sa.Integer(), nullable=True),
    sa.Column('ahrefs_eb', sa.Integer(), nullable=True),
    sa.Column('ahrefs_rd', sa.Integer(), nullable=True),
    sa.Column('ahrefs_dofollow', sa.Integer(), nullable=True),
    sa.Column('ahrefs_ips', sa.Integer(), nullable=True),
    sa.Column('semrush_rank', sa.Integer(), nullable=True),
    sa.Column('semrush_keywords', sa.Integer(), nullable=True),
    sa.Column('fb_comments', sa.Integer(), nullable=True),
    sa.Column('fb_shares', sa.Integer(), nullable=True),
    sa.Column('fb_reactions', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('unavailable_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.String(), nullable=False),
    sa.Column('creation_time', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.String(), nullable=False),
    sa.Column('expiration_time', sa.String(), nullable=False),
    sa.Column('name_servers', sa.String(), nullable=True),
    sa.Column('updated_date', sa.String(), nullable=False),
    sa.Column('updated_time', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('user_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('user_envs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jan_ip', sa.String(), nullable=True),
    sa.Column('jan_port', sa.Integer(), nullable=True),
    sa.Column('jan_prefix', sa.String(), nullable=True),
    sa.Column('open_ai_api_key', sa.String(), nullable=True),
    sa.Column('google_search_api_key', sa.String(), nullable=True),
    sa.Column('google_cx', sa.String(), nullable=True),
    sa.Column('myaddr_api_key', sa.String(), nullable=True),
    sa.Column('porkbun_api_key', sa.String(), nullable=True),
    sa.Column('porkbun_secret', sa.String(), nullable=True),
    sa.Column('czds_login', sa.String(), nullable=True),
    sa.Column('czds_password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('focus_keyword', sa.String(), nullable=False),
    sa.Column('avg_monthly_searches', sa.Integer(), nullable=True),
    sa.Column('keyword_difficulty', sa.Integer(), nullable=True),
    sa.Column('high_cpc', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('low_cpc', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['user_domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('focus_keyword')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('html_text', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('title_of_cover_image', sa.String(), nullable=True),
    sa.Column('alt_of_cover_image', sa.String(), nullable=True),
    sa.Column('meta_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('total_results', sa.Integer(), nullable=True),
    sa.Column('min_word_count', sa.Integer(), nullable=True),
    sa.Column('max_word_count', sa.Integer(), nullable=True),
    sa.Column('min_num_paragraphs', sa.Integer(), nullable=True),
    sa.Column('max_num_paragraphs', sa.Integer(), nullable=True),
    sa.Column('min_num_h1_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h1_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_h2_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h2_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_h3_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h3_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_h4_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h4_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_h5_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h5_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_h6_headers', sa.Integer(), nullable=True),
    sa.Column('max_num_h6_headers', sa.Integer(), nullable=True),
    sa.Column('min_total_headers', sa.Integer(), nullable=True),
    sa.Column('max_total_headers', sa.Integer(), nullable=True),
    sa.Column('min_num_images', sa.Integer(), nullable=True),
    sa.Column('max_num_images', sa.Integer(), nullable=True),
    sa.Column('min_num_links', sa.Integer(), nullable=True),
    sa.Column('max_num_links', sa.Integer(), nullable=True),
    sa.Column('min_num_internal_links', sa.Integer(), nullable=True),
    sa.Column('max_num_internal_links', sa.Integer(), nullable=True),
    sa.Column('min_num_external_links', sa.Integer(), nullable=True),
    sa.Column('max_num_external_links', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_stats')
    op.drop_table('articles')
    op.drop_table('keywords')
    op.drop_table('user_envs')
    op.drop_table('user_domains')
    op.drop_table('unavailable_domains')
    op.drop_table('token_blacklist')
    op.drop_table('available_domains')
    op.drop_table('users')
    op.drop_table('domains')
    # ### end Alembic commands ###
