"""empty message

Revision ID: 8a3e78465dbf
Revises: d5de80622ba7
Create Date: 2024-06-28 21:29:04.610675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e78465dbf'
down_revision = 'd5de80622ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_ai_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_search_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('google_cx', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('myaddr_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('porkbun_api_key', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('porkbun_secret', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.drop_column('porkbun_secret')
        batch_op.drop_column('porkbun_api_key')
        batch_op.drop_column('myaddr_api_key')
        batch_op.drop_column('google_cx')
        batch_op.drop_column('google_search_api_key')
        batch_op.drop_column('open_ai_api_key')

    # ### end Alembic commands ###
