"""empty message

Revision ID: a7592261d5b1
Revises: 6f63996c9609
Create Date: 2024-07-04 00:08:44.596143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7592261d5b1'
down_revision = '6f63996c9609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['domain_id'])

    with op.batch_alter_table('unavailable_domains', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['domain_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailable_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
