"""empty message

Revision ID: a97eb9a44c2f
Revises: a5e71f72b787
Create Date: 2024-07-25 00:24:03.515850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97eb9a44c2f'
down_revision = 'a5e71f72b787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.drop_column('ollama_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ollama_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
