"""empty message

Revision ID: b1e5819abe56
Revises: 096400439941
Create Date: 2024-05-10 00:30:34.274282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e5819abe56'
down_revision = '096400439941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_value', sa.String(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('codename',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('codename',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('hashed_value')

    # ### end Alembic commands ###
