"""empty message

Revision ID: c2a507576a99
Revises: 0e9798dc1f3b
Create Date: 2024-07-24 21:29:31.792129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a507576a99'
down_revision = '0e9798dc1f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ollama_ip', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ollama_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ollama_web_address', sa.String(), nullable=True))
        batch_op.drop_column('jan_prefix')
        batch_op.drop_column('jan_ip')
        batch_op.drop_column('jan_port')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jan_port', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jan_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('jan_prefix', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('ollama_web_address')
        batch_op.drop_column('ollama_port')
        batch_op.drop_column('ollama_ip')

    # ### end Alembic commands ###
