"""empty message

Revision ID: d9c36cd41053
Revises: 7f282bddb6ac
Create Date: 2024-07-22 20:59:02.347069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c36cd41053'
down_revision = '7f282bddb6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domdetailer_api_key', sa.String(), nullable=True))
        batch_op.drop_column('myaddr_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_envs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('myaddr_api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('domdetailer_api_key')

    # ### end Alembic commands ###
