"""empty message

Revision ID: e01f6adc5e85
Revises: d9c36cd41053
Create Date: 2024-07-22 23:09:42.332641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01f6adc5e85'
down_revision = 'd9c36cd41053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moz_links', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moz_rank', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('moz_trust', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('moz_spam', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stumbles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pinterest_pins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_stat', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('majestic_links', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ref_domains', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ref_edu', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ref_gov', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ref_subnets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ips', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_cf', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_tf', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf0_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf0_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf1_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf1_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf2_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('majestic_ttf2_value', sa.Integer(), nullable=True))
        batch_op.drop_column('semrush_keywords')
        batch_op.drop_column('ahrefs_ips')
        batch_op.drop_column('ahrefs_eb')
        batch_op.drop_column('ahrefs_dr')
        batch_op.drop_column('ahrefs_dofollow')
        batch_op.drop_column('semrush_rank')
        batch_op.drop_column('fb_reactions')
        batch_op.drop_column('ahrefs_rd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('available_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ahrefs_rd', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fb_reactions', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semrush_rank', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ahrefs_dofollow', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ahrefs_dr', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ahrefs_eb', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ahrefs_ips', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semrush_keywords', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('majestic_ttf2_value')
        batch_op.drop_column('majestic_ttf2_name')
        batch_op.drop_column('majestic_ttf1_value')
        batch_op.drop_column('majestic_ttf1_name')
        batch_op.drop_column('majestic_ttf0_value')
        batch_op.drop_column('majestic_ttf0_name')
        batch_op.drop_column('majestic_tf')
        batch_op.drop_column('majestic_cf')
        batch_op.drop_column('majestic_ips')
        batch_op.drop_column('majestic_ref_subnets')
        batch_op.drop_column('majestic_ref_gov')
        batch_op.drop_column('majestic_ref_edu')
        batch_op.drop_column('majestic_ref_domains')
        batch_op.drop_column('majestic_links')
        batch_op.drop_column('majestic_stat')
        batch_op.drop_column('pinterest_pins')
        batch_op.drop_column('stumbles')
        batch_op.drop_column('moz_spam')
        batch_op.drop_column('moz_trust')
        batch_op.drop_column('moz_rank')
        batch_op.drop_column('moz_links')

    # ### end Alembic commands ###
